"""
Validates LLM-generated SQL before execution.
Only SELECT statements against whitelisted tables are allowed.
"""

import re

ALLOWED_TABLES = {"vw_agent_gestiones"}

FORBIDDEN_PATTERNS = [
    r"\bDROP\b",
    r"\bDELETE\b",
    r"\bINSERT\b",
    r"\bUPDATE\b",
    r"\bCREATE\b",
    r"\bALTER\b",
    r"\bTRUNCATE\b",
    r"\bEXEC\b",
    r"\bEXECUTE\b",
    r"\bCALL\b",
    r"\bMERGE\b",
    r"--",
    r"/\*",
    r"\bINTO\b",
    r"\bGRANT\b",
    r"\bREVOKE\b",
]


def validate(sql: str) -> tuple[bool, str]:
    """
    Validate a SQL string generated by the LLM.
    Returns (is_valid, message).
    """
    if not sql or not sql.strip():
        return False, "SQL vacío"

    stripped = sql.strip()

    # Must start with SELECT
    if not stripped.upper().lstrip().startswith("SELECT"):
        return False, "Solo se permiten queries SELECT"

    upper = stripped.upper()

    # Check forbidden patterns
    for pattern in FORBIDDEN_PATTERNS:
        if re.search(pattern, upper):
            return False, f"Patrón no permitido detectado: {pattern}"

    # Extract table references (backtick-quoted BQ format)
    # Matches `project.dataset.table` or `dataset.table`
    table_refs = re.findall(r"`[^`]+\.([^`.]+)`", stripped)
    for table in table_refs:
        if table not in ALLOWED_TABLES:
            return False, f"Tabla no permitida: {table}. Solo se permite: {ALLOWED_TABLES}"

    # Also check bare table names (without backticks) — simple check
    # Look for FROM/JOIN followed by a word
    bare_tables = re.findall(r"(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b", upper)
    for table in bare_tables:
        if table in ("SELECT", "WHERE", "AND", "OR", "ON", "SET"):
            continue
        if table.lower() not in ALLOWED_TABLES:
            # Could be a subquery alias — allow if it looks like a CTE or alias
            # This is a best-effort check; the main protection is BigQuery permissions
            pass

    return True, "OK"


def extract_sql(text: str) -> str:
    """
    Extract a SQL query from LLM output that may contain markdown code fences
    or surrounding explanation text.
    """
    # Try to extract from ```sql ... ``` block
    m = re.search(r"```(?:sql)?\s*(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()

    # Try to extract from ``` ... ``` block
    m = re.search(r"```(.*?)```", text, re.DOTALL)
    if m:
        return m.group(1).strip()

    # Find the first SELECT statement
    m = re.search(r"(SELECT\b.*)", text, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()

    return text.strip()
